parameters:

services:
    sip.resource.form.show.image.type:
        class: SIP\ResourceBundle\Form\Type\ShowImageType
        tags:
            - { name: form.type, alias: show_sonata_image }

    sip_resource.helper.settings:
        class: SIP\ResourceBundle\Helper\SettingsHelper
        arguments: ['@service_container']

    sip_resource.twig.settings:
            class: SIP\ResourceBundle\Twig\Extension\SettingsExtension
            arguments: ['@service_container']
            tags: [{ name: twig.extension }]
    
    sip.object.listener:
        class: SIP\ResourceBundle\EventListener\ObjectEventListener
        tags:            
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    sonata.media.provider.image:
        class: SIP\ResourceBundle\Provider\ImageProvider
        arguments:
            - sonata.media.provider.image
            - @sonata.media.filesystem.local
            - @sonata.media.cdn.server
            - @sonata.media.generator.default
            - @sonata.media.thumbnail.format
            - ['jpg', 'png', 'jpeg']
            - ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png',]
            - @sonata.media.adapter.image.gd
            - @sonata.media.metadata.proxy
        tags: [{ name: sonata.media.provider }]
        calls:
            - [ setTemplates, [ {helper_thumbnail: SonataMediaBundle:Provider:thumbnail.html.twig, helper_view: SonataMediaBundle:Provider:view_image.html.twig} ] ]
            - [ setContainer, [@service_container]]

    meta.twig_extension:
        class: SIP\ResourceBundle\Twig\Extension\MetaExtension
        arguments:
              doctrine: "@doctrine"
        public: false
        tags:
            - { name: twig.extension }